name: mikerowan
favicon: null
layout_spectrum: 0.04155169450677931
typography_spectrum: 0.24264476471580565
title: mikerowan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.03201604331843555
  lightness: 0.04009386780671775
  saturation: 0.4792393937241286
  rhythmicContrast: 0.9454456563107669
purpose: []
